baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Worthy of a penny"
theme = 'tailbliss'

ignorefiles = [
  "/themes/tailbliss/content/.*",
]
[outputformats]
  [outputformats.SearchIndex]
    baseName = "search"
    mediaType = "application/json"
[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
enableInlineShortcodes = true

[params]
author = "Marisa Lopez"
github = "https://github.com/celina-lopez"
sitename = "Worthyofapenny"
description = "thoughts worthy of a penny"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "Tags"

